export const soundCategories = [
  {
    id: "ambient",
    title: "Ambient",
    subtitle: "Слои, задающие настроение",
    icon: "assets/icons/ambient.png",
    sounds: [
      {
        id: "Acreepy_dark",
        title: "A Creepy Dark",
        description: "Мрачный низкий гул",
        file: "sounds/wh/ambient/Acreepy_dark.mp3",
        icon: "assets/icons/deep-void.png",
        defaultVolume: 0.5,
      },
      {
        id: "Adark_horror",
        title: "A Dark Horror",
        description: "Мистический шум",
        file: "sounds/wh/ambient/Adark_horror.mp3",
        icon: "assets/icons/warp-rift.png",
        defaultVolume: 0.3,
      },
      {
        id: "Agrim",
        title: "A Grim",
        description: "Тревожный фон",
        file: "sounds/wh/ambient/Agrim.mp3",
        icon: "assets/icons/gellar-field.png",
        defaultVolume: 0.65,
      },
      {
        id: "Ahorror",
        title: "A horror",
        description: "Мрачный медленный шум",
        file: "sounds/wh/ambient/Ahorror.mp3",
        icon: "assets/icons/starship-engines.png",
        defaultVolume: 0.9,
      },
      {
        id: "Amystical",
        title: "A Mystical",
        description: "Загадочные туки",
        file: "sounds/wh/ambient/Amystical.mp3",
        icon: "assets/icons/fortress-ambience.png",
        defaultVolume: 0.6,
      },
      {
        id: "asylum",
        title: "Asylum",
        description: "Стоны и мольбы",
        file: "sounds/wh/ambient/asylum.mp3",
        icon: "assets/icons/busy-city.png",
        defaultVolume: 0.3,
      },
      {
        id: "crime_background",
        title: "Crime BG",
        description: "Сбор улик",
        file: "sounds/wh/ambient/crime_background.mp3",
        icon: "assets/icons/cathedral-organ.png",
        defaultVolume: 0.65,
      },
      {
        id: "detective",
        title: "Detective",
        description: "Расследование преступления",
        file: "sounds/wh/ambient/detective.mp3",
        icon: "assets/icons/administratum-archive.png",
        defaultVolume: 0.7,
      },
      {
        id: "timer_search",
        title: "Timer Search",
        description: "Тревожный таймер",
        file: "sounds/wh/ambient/timer_search.mp3",
        icon: "assets/icons/demon-breath.png",
        defaultVolume: 0.5,
      },
      {
        id: "timer_tension",
        title: "Timer Tension",
        description: "Напряженный таймер",
        file: "sounds/wh/ambient/timer_tension.mp3",
        icon: "assets/icons/strong-wind.png",
        defaultVolume: 0.7,
      },
    ],
  },

  {
    id: "music",
    title: "Music",
    subtitle: "Музыка для игры",
    icon: "assets/icons/warp-echo.png",
    sounds: [
      {
        id: "pulse-tension",
        title: "Pulse Tension",
        description: "Пульсирующий напряженный",
        file: "sounds/wh/music/pulse_tension.mp3",
        icon: "assets/icons/psyker-pulse.png",
        defaultVolume: 0.7,
      },
      {
        id: "terrorwave",
        title: "Terrorwave",
        description: "Высокие струнные, тревожная",
        file: "sounds/wh/music/terrorwave.mp3",
        icon: "assets/icons/wind-blow.png",
        defaultVolume: 0.6,
      },
      {
        id: "01_Jazz",
        title: "Jazz #1",
        description: "Первая часть",
        file: "sounds/wh/music/01_Jazz.mp3",
        icon: "assets/icons/warp-battle.png",
        defaultVolume: 0.3,
      },
      {
        id: "02_Jazz",
        title: "Jazz #2",
        description: "Вторая часть",
        file: "sounds/wh/music/02_Jazz.mp3",
        icon: "assets/icons/warp-battle.png",
        defaultVolume: 0.3,
      },
      {
        id: "03_Jazz",
        title: "Jazz #3",
        description: "Третья часть",
        file: "sounds/wh/music/03_Jazz.mp3",
        icon: "assets/icons/warp-battle.png",
        defaultVolume: 0.3,
      },
      {
        id: "04_Jazz",
        title: "Jazz #4",
        description: "Четвертая часть",
        file: "sounds/wh/music/04_Jazz.mp3",
        icon: "assets/icons/warp-battle.png",
        defaultVolume: 0.3,
      },
      {
        id: "01_Innsmouth",
        title: "Innsmouth #1",
        description: "Первая часть",
        file: "sounds/wh/music/01_Innsmouth.mp3",
        icon: "assets/icons/light-rain.png",
        defaultVolume: 0.45,
      },
      {
        id: "02_Innsmouth",
        title: "Innsmouth #2",
        description: "Вторая часть",
        file: "sounds/wh/music/02_Innsmouth.mp3",
        icon: "assets/icons/light-rain.png",
        defaultVolume: 0.45,
      },
      {
        id: "03_Innsmouth",
        title: "Innsmouth #3",
        description: "Третья часть",
        file: "sounds/wh/music/03_Innsmouth.mp3",
        icon: "assets/icons/light-rain.png",
        defaultVolume: 0.45,
      },
      {
        id: "04_Innsmouth",
        title: "Innsmouth #4",
        description: "Четвертая часть",
        file: "sounds/wh/music/04_Innsmouth.mp3",
        icon: "assets/icons/light-rain.png",
        defaultVolume: 0.45,
      },
      {
        id: "05_Innsmouth",
        title: "Innsmouth #5",
        description: "Пятая часть",
        file: "sounds/wh/music/05_Innsmouth.mp3",
        icon: "assets/icons/light-rain.png",
        defaultVolume: 0.45,
      },
    ],
  },
  
  {
    id: "battle",
    title: "Battle",
    subtitle: "Битвы, тревога и бой с боссом",
    icon: "assets/icons/battle.png",
    sounds: [
      {
        id: "combat-tension",
        title: "Combat Tension",
        description: "Напряженная ситуация перед боем",
        file: "sounds/wh/battle/combat-tension.m4a",
        icon: "assets/icons/combat-tension.png",
        defaultVolume: 0.8,
      },
      {
        id: "countdown",
        title: "Countdown",
        description: "Неизбежная катастрофа",
        file: "sounds/wh/battle/countdown.m4a",
        icon: "assets/icons/countdown.png",
        defaultVolume: 0.30,
      },
      {
        id: "clock_darkness",
        title: "Clock Darkness",
        description: "Величественное, непостижимое, хоррор",
        file: "sounds/wh/battle/clock_darkness.mp3",
        icon: "assets/icons/warp-battle.png",
        defaultVolume: 0.55,
      },
      {
        id: "pursuit",
        title: "Pursuit",
        description: "Напряженные струнные",
        file: "sounds/wh/battle/pursuit.mp3",
        icon: "assets/icons/daemonhost.png",
        defaultVolume: 0.32,
      },
      {
        id: "boss-fight",
        title: "Boss Fight",
        description: "Эпический хаос, низкие удары",
        file: "sounds/wh/battle/boss-fight.m4a",
        icon: "assets/icons/boss-fight.png",
        defaultVolume: 0.55,
      },
    ],
  },

  {
    id: "effects",
    title: "Effects",
    subtitle: "Отдельные звуковые слои и технические шумы",
    icon: "assets/icons/effects.png",
    sounds: [
      {
        id: "chase_loop",
        title: "Chase Loop",
        description: "Погоня",
        file: "sounds/wh/effects/chase_loop.wav",
        icon: "assets/icons/machine-spirit.png",
        defaultVolume: 0.45,
      },
      {
        id: "isolated_foghorn",
        title: "Isolated Foghorn",
        description: "Зловещий сигнал",
        file: "sounds/wh/effects/isolated_foghorn.mp3",
        icon: "assets/icons/scanner-ping.png",
        defaultVolume: 1.0,
      },
      {
        id: "vision",
        title: "Vision",
        description: "Видение",
        file: "sounds/wh/effects/vision.mp3",
        icon: "assets/icons/cogitator.png",
        defaultVolume: 0.35,
      },
      {
        id: "yandere_laugh",
        title: "Yandere Laugh",
        description: "Зловещий женский смех",
        file: "sounds/wh/effects/yandere_laugh.mp3",
        icon: "assets/icons/pressure-release.png",
        defaultVolume: 0.6,
      },
      {
        id: "loony",
        title: "Loony Loop",
        description: "Тревожная бас-гитара",
        file: "sounds/wh/effects/Loony1.mp3",
        icon: "assets/icons/daemonhost.png",
        defaultVolume: 0.25,
      },
      {
        id: "fireplace",
        title: "Fireplace",
        description: "Камин без музыки",
        file: "sounds/wh/effects/fireplace.mp3",
        icon: "assets/icons/countdown.png",
        defaultVolume: 0.85,
      },
    ],
  },

  {
    id: "weather",
    title: "Weather",
    subtitle: "Погодные эффекты разных мест",
    icon: "assets/icons/weather.png",
    sounds: [
      {
        id: "forest_loop",
        title: "Forest",
        description: "Звуки природы",
        file: "sounds/wh/weather/forest_loop_test.mp3",
        icon: "assets/icons/light-rain.png",
        defaultVolume: 0.7,
      },
      {
        id: "lightrain_loop",
        title: "Light Rain",
        description: "Дождь",
        file: "sounds/wh/weather/light_rain_loop_new.mp3",
        icon: "assets/icons/heavy-rain.png",
        defaultVolume: 0.80,
      },
      {
        id: "rain_loop",
        title: "Light rain 2",
        description: "Вторая вариация",
        file: "sounds/wh/weather/rain_loop_new.mp3",
        icon: "assets/icons/thunderstorm.png",
        defaultVolume: 0.40,
      },
      {
        id: "seagull_loop",
        title: "Seagull",
        description: "Чайки далеко",
        file: "sounds/wh/weather/seagull_loop.mp3",
        icon: "assets/icons/deep-void.png",
        defaultVolume: 0.85,
      },
      {
        id: "seawaves_loop",
        title: "Seawaves",
        description: "Волны близко",
        file: "sounds/wh/weather/seawaves_loop.mp3",
        icon: "assets/icons/fortress-ambience.png",
        defaultVolume: 0.10,
      },
      {
        id: "thunderstorm_loop",
        title: "Thunderstorm",
        description: "Гроза и дождь",
        file: "sounds/wh/weather/thurderstopm_loop_new.mp3",
        icon: "assets/icons/daemonhost.png",
        defaultVolume: 0.3,
      },
      {
        id: "wind_loop",
        title: "Wind",
        description: "Сильный ветер",
        file: "sounds/wh/weather/wind_loop_new.mp3",
        icon: "assets/icons/strong-wind.png",
        defaultVolume: 0.4,
      },
    ],
  },
];
